// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Order.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Order_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Order_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Order_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Order_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Order_2eproto;
namespace Purchase {
class Order;
struct OrderDefaultTypeInternal;
extern OrderDefaultTypeInternal _Order_default_instance_;
class orderItem;
struct orderItemDefaultTypeInternal;
extern orderItemDefaultTypeInternal _orderItem_default_instance_;
}  // namespace Purchase
PROTOBUF_NAMESPACE_OPEN
template<> ::Purchase::Order* Arena::CreateMaybeMessage<::Purchase::Order>(Arena*);
template<> ::Purchase::orderItem* Arena::CreateMaybeMessage<::Purchase::orderItem>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Purchase {

// ===================================================================

class orderItem final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Purchase.orderItem) */ {
 public:
  inline orderItem() : orderItem(nullptr) {}
  ~orderItem() override;
  explicit PROTOBUF_CONSTEXPR orderItem(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  orderItem(const orderItem& from);
  orderItem(orderItem&& from) noexcept
    : orderItem() {
    *this = ::std::move(from);
  }

  inline orderItem& operator=(const orderItem& from) {
    CopyFrom(from);
    return *this;
  }
  inline orderItem& operator=(orderItem&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const orderItem& default_instance() {
    return *internal_default_instance();
  }
  static inline const orderItem* internal_default_instance() {
    return reinterpret_cast<const orderItem*>(
               &_orderItem_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(orderItem& a, orderItem& b) {
    a.Swap(&b);
  }
  inline void Swap(orderItem* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(orderItem* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  orderItem* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<orderItem>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const orderItem& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const orderItem& from) {
    orderItem::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(orderItem* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Purchase.orderItem";
  }
  protected:
  explicit orderItem(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDescFieldNumber = 2,
    kCodeFieldNumber = 1,
    kQtyFieldNumber = 3,
    kPriceFieldNumber = 4,
  };
  // string desc = 2;
  void clear_desc();
  const std::string& desc() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_desc(ArgT0&& arg0, ArgT... args);
  std::string* mutable_desc();
  PROTOBUF_NODISCARD std::string* release_desc();
  void set_allocated_desc(std::string* desc);
  private:
  const std::string& _internal_desc() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_desc(const std::string& value);
  std::string* _internal_mutable_desc();
  public:

  // int32 code = 1;
  void clear_code();
  int32_t code() const;
  void set_code(int32_t value);
  private:
  int32_t _internal_code() const;
  void _internal_set_code(int32_t value);
  public:

  // int32 qty = 3;
  void clear_qty();
  int32_t qty() const;
  void set_qty(int32_t value);
  private:
  int32_t _internal_qty() const;
  void _internal_set_qty(int32_t value);
  public:

  // double price = 4;
  void clear_price();
  double price() const;
  void set_price(double value);
  private:
  double _internal_price() const;
  void _internal_set_price(double value);
  public:

  // @@protoc_insertion_point(class_scope:Purchase.orderItem)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr desc_;
    int32_t code_;
    int32_t qty_;
    double price_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Order_2eproto;
};
// -------------------------------------------------------------------

class Order final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Purchase.Order) */ {
 public:
  inline Order() : Order(nullptr) {}
  ~Order() override;
  explicit PROTOBUF_CONSTEXPR Order(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Order(const Order& from);
  Order(Order&& from) noexcept
    : Order() {
    *this = ::std::move(from);
  }

  inline Order& operator=(const Order& from) {
    CopyFrom(from);
    return *this;
  }
  inline Order& operator=(Order&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Order& default_instance() {
    return *internal_default_instance();
  }
  static inline const Order* internal_default_instance() {
    return reinterpret_cast<const Order*>(
               &_Order_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Order& a, Order& b) {
    a.Swap(&b);
  }
  inline void Swap(Order* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Order* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Order* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Order>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Order& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Order& from) {
    Order::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Order* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Purchase.Order";
  }
  protected:
  explicit Order(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kItemFieldNumber = 3,
    kVendorFieldNumber = 2,
    kIdFieldNumber = 1,
  };
  // repeated .Purchase.orderItem item = 3;
  int item_size() const;
  private:
  int _internal_item_size() const;
  public:
  void clear_item();
  ::Purchase::orderItem* mutable_item(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Purchase::orderItem >*
      mutable_item();
  private:
  const ::Purchase::orderItem& _internal_item(int index) const;
  ::Purchase::orderItem* _internal_add_item();
  public:
  const ::Purchase::orderItem& item(int index) const;
  ::Purchase::orderItem* add_item();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Purchase::orderItem >&
      item() const;

  // string vendor = 2;
  void clear_vendor();
  const std::string& vendor() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_vendor(ArgT0&& arg0, ArgT... args);
  std::string* mutable_vendor();
  PROTOBUF_NODISCARD std::string* release_vendor();
  void set_allocated_vendor(std::string* vendor);
  private:
  const std::string& _internal_vendor() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_vendor(const std::string& value);
  std::string* _internal_mutable_vendor();
  public:

  // int32 id = 1;
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Purchase.Order)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Purchase::orderItem > item_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr vendor_;
    int32_t id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Order_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// orderItem

// int32 code = 1;
inline void orderItem::clear_code() {
  _impl_.code_ = 0;
}
inline int32_t orderItem::_internal_code() const {
  return _impl_.code_;
}
inline int32_t orderItem::code() const {
  // @@protoc_insertion_point(field_get:Purchase.orderItem.code)
  return _internal_code();
}
inline void orderItem::_internal_set_code(int32_t value) {
  
  _impl_.code_ = value;
}
inline void orderItem::set_code(int32_t value) {
  _internal_set_code(value);
  // @@protoc_insertion_point(field_set:Purchase.orderItem.code)
}

// string desc = 2;
inline void orderItem::clear_desc() {
  _impl_.desc_.ClearToEmpty();
}
inline const std::string& orderItem::desc() const {
  // @@protoc_insertion_point(field_get:Purchase.orderItem.desc)
  return _internal_desc();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void orderItem::set_desc(ArgT0&& arg0, ArgT... args) {
 
 _impl_.desc_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Purchase.orderItem.desc)
}
inline std::string* orderItem::mutable_desc() {
  std::string* _s = _internal_mutable_desc();
  // @@protoc_insertion_point(field_mutable:Purchase.orderItem.desc)
  return _s;
}
inline const std::string& orderItem::_internal_desc() const {
  return _impl_.desc_.Get();
}
inline void orderItem::_internal_set_desc(const std::string& value) {
  
  _impl_.desc_.Set(value, GetArenaForAllocation());
}
inline std::string* orderItem::_internal_mutable_desc() {
  
  return _impl_.desc_.Mutable(GetArenaForAllocation());
}
inline std::string* orderItem::release_desc() {
  // @@protoc_insertion_point(field_release:Purchase.orderItem.desc)
  return _impl_.desc_.Release();
}
inline void orderItem::set_allocated_desc(std::string* desc) {
  if (desc != nullptr) {
    
  } else {
    
  }
  _impl_.desc_.SetAllocated(desc, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.desc_.IsDefault()) {
    _impl_.desc_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Purchase.orderItem.desc)
}

// int32 qty = 3;
inline void orderItem::clear_qty() {
  _impl_.qty_ = 0;
}
inline int32_t orderItem::_internal_qty() const {
  return _impl_.qty_;
}
inline int32_t orderItem::qty() const {
  // @@protoc_insertion_point(field_get:Purchase.orderItem.qty)
  return _internal_qty();
}
inline void orderItem::_internal_set_qty(int32_t value) {
  
  _impl_.qty_ = value;
}
inline void orderItem::set_qty(int32_t value) {
  _internal_set_qty(value);
  // @@protoc_insertion_point(field_set:Purchase.orderItem.qty)
}

// double price = 4;
inline void orderItem::clear_price() {
  _impl_.price_ = 0;
}
inline double orderItem::_internal_price() const {
  return _impl_.price_;
}
inline double orderItem::price() const {
  // @@protoc_insertion_point(field_get:Purchase.orderItem.price)
  return _internal_price();
}
inline void orderItem::_internal_set_price(double value) {
  
  _impl_.price_ = value;
}
inline void orderItem::set_price(double value) {
  _internal_set_price(value);
  // @@protoc_insertion_point(field_set:Purchase.orderItem.price)
}

// -------------------------------------------------------------------

// Order

// int32 id = 1;
inline void Order::clear_id() {
  _impl_.id_ = 0;
}
inline int32_t Order::_internal_id() const {
  return _impl_.id_;
}
inline int32_t Order::id() const {
  // @@protoc_insertion_point(field_get:Purchase.Order.id)
  return _internal_id();
}
inline void Order::_internal_set_id(int32_t value) {
  
  _impl_.id_ = value;
}
inline void Order::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:Purchase.Order.id)
}

// string vendor = 2;
inline void Order::clear_vendor() {
  _impl_.vendor_.ClearToEmpty();
}
inline const std::string& Order::vendor() const {
  // @@protoc_insertion_point(field_get:Purchase.Order.vendor)
  return _internal_vendor();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Order::set_vendor(ArgT0&& arg0, ArgT... args) {
 
 _impl_.vendor_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Purchase.Order.vendor)
}
inline std::string* Order::mutable_vendor() {
  std::string* _s = _internal_mutable_vendor();
  // @@protoc_insertion_point(field_mutable:Purchase.Order.vendor)
  return _s;
}
inline const std::string& Order::_internal_vendor() const {
  return _impl_.vendor_.Get();
}
inline void Order::_internal_set_vendor(const std::string& value) {
  
  _impl_.vendor_.Set(value, GetArenaForAllocation());
}
inline std::string* Order::_internal_mutable_vendor() {
  
  return _impl_.vendor_.Mutable(GetArenaForAllocation());
}
inline std::string* Order::release_vendor() {
  // @@protoc_insertion_point(field_release:Purchase.Order.vendor)
  return _impl_.vendor_.Release();
}
inline void Order::set_allocated_vendor(std::string* vendor) {
  if (vendor != nullptr) {
    
  } else {
    
  }
  _impl_.vendor_.SetAllocated(vendor, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.vendor_.IsDefault()) {
    _impl_.vendor_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Purchase.Order.vendor)
}

// repeated .Purchase.orderItem item = 3;
inline int Order::_internal_item_size() const {
  return _impl_.item_.size();
}
inline int Order::item_size() const {
  return _internal_item_size();
}
inline void Order::clear_item() {
  _impl_.item_.Clear();
}
inline ::Purchase::orderItem* Order::mutable_item(int index) {
  // @@protoc_insertion_point(field_mutable:Purchase.Order.item)
  return _impl_.item_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Purchase::orderItem >*
Order::mutable_item() {
  // @@protoc_insertion_point(field_mutable_list:Purchase.Order.item)
  return &_impl_.item_;
}
inline const ::Purchase::orderItem& Order::_internal_item(int index) const {
  return _impl_.item_.Get(index);
}
inline const ::Purchase::orderItem& Order::item(int index) const {
  // @@protoc_insertion_point(field_get:Purchase.Order.item)
  return _internal_item(index);
}
inline ::Purchase::orderItem* Order::_internal_add_item() {
  return _impl_.item_.Add();
}
inline ::Purchase::orderItem* Order::add_item() {
  ::Purchase::orderItem* _add = _internal_add_item();
  // @@protoc_insertion_point(field_add:Purchase.Order.item)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Purchase::orderItem >&
Order::item() const {
  // @@protoc_insertion_point(field_list:Purchase.Order.item)
  return _impl_.item_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Purchase

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Order_2eproto
