/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyTestJNI */

#ifndef _Included_MyTestJNI
#define _Included_MyTestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyTestJNI
 * Method:    CppMethod
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_MyTestJNI_CppMethod
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
